site_name: Documentation site de CHARTRES
theme:
  name: material
  language: fr
  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
