site_name: Documentation site de CHARTRES
theme:
  name: material
  language: fr
  palette:
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: "#C70039"  
      accent: "#FF5733"  
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: "##900C3F"  
      accent: "#FF5733"   
