site_name: Documentation site de CHARTRES
theme:
  name: material
  language: fr
  palette:
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: "#0cd60f"  
      accent: "#d7e100"  
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: "#04ae07"  
      accent: "#d7e100"   
